/*

Relacion N:N
La tabla de informacion de los Alumnos se relaciona con la tabla de Materias, donde un alumno puede cursar mas de una materia y 
una materia puede ser relacionada con varios registro de la tabla de alumnos.

*/

CREATE TABLE MATERIA(
	ID_MATERIA INT NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(15) NOT NULL,
	HORARIO VARCHAR(10) NOT NULL, 
	TITULAR VARCHAR(50) NOT NULL
)
GO
CREATE TABLE ALUMNOS(
	ID_ALUMNO INT NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL,
	APELLIDO VARCHAR(50) NOT NULL
)
GO
CREATE TABLE MATERIAS_X_ALUMNO(
	ID_ALUMNO INT NOT NULL,
	ID_MATERIA INT NOT NULL,
	PRIMARY KEY (ID_MATERIA, ID_ALUMNO),
	FOREIGN KEY (ID_ALUMNO) REFERENCES ALUMNOS (ID_ALUMNO),
	FOREIGN KEY (ID_MATERIA) REFERENCES MATERIA (ID_MATERIA)
)